package markdown

import (
	"fmt"
	"strings"

	"github.com/fblissjr/crx2md/internal/extension"
)

// Render produces an LLM-optimized markdown document from an Extension.
func Render(ext *extension.Extension, includeBinary bool) string {
	var b strings.Builder

	renderHeader(&b, ext)
	renderMetadata(&b, ext)
	renderFileTree(&b, ext, includeBinary)
	sourceCount, binaryCount := renderSourceFiles(&b, ext, includeBinary)
	renderFooter(&b, sourceCount, binaryCount)

	return b.String()
}

func renderHeader(b *strings.Builder, ext *extension.Extension) {
	name := ext.Manifest.Name
	if name == "" {
		name = "Unknown Extension"
	}
	fmt.Fprintf(b, "# Chrome Extension: %s\n\n", name)
}

func renderMetadata(b *strings.Builder, ext *extension.Extension) {
	b.WriteString("## Metadata\n")
	fmt.Fprintf(b, "- **Version**: %s\n", ext.Manifest.Version)
	fmt.Fprintf(b, "- **Manifest Version**: %d\n", ext.Manifest.ManifestVersion)
	fmt.Fprintf(b, "- **Description**: %s\n", ext.Manifest.Description)

	if len(ext.Manifest.Permissions) > 0 {
		fmt.Fprintf(b, "- **Permissions**: %s\n", strings.Join(ext.Manifest.Permissions, ", "))
	}
	b.WriteString("\n")
}

func renderFileTree(b *strings.Builder, ext *extension.Extension, includeBinary bool) {
	b.WriteString("## File Tree\n```\n")
	for _, f := range ext.Files {
		if f.IsCode {
			fmt.Fprintf(b, "%s\n", f.Path)
		} else if includeBinary {
			fmt.Fprintf(b, "%s (binary, %s)\n", f.Path, formatSize(f.Size))
		}
	}
	b.WriteString("```\n\n")
}

func renderSourceFiles(b *strings.Builder, ext *extension.Extension, includeBinary bool) (sourceCount, binaryCount int) {
	b.WriteString("## Source Files\n\n")

	for _, f := range ext.Files {
		if f.IsCode {
			sourceCount++
			fmt.Fprintf(b, "### `%s`\n", f.Path)
			fmt.Fprintf(b, "```%s\n", f.Language)
			b.Write(f.Content)
			// Ensure content ends with newline before closing fence
			if len(f.Content) > 0 && f.Content[len(f.Content)-1] != '\n' {
				b.WriteByte('\n')
			}
			b.WriteString("```\n\n")
		} else {
			binaryCount++
			if includeBinary {
				fmt.Fprintf(b, "### `%s`\n", f.Path)
				fmt.Fprintf(b, "*Binary file, %s*\n\n", formatSize(f.Size))
			}
		}
	}

	return sourceCount, binaryCount
}

func renderFooter(b *strings.Builder, sourceCount, binaryCount int) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "*Generated by crx2md | %d source files rendered", sourceCount)
	if binaryCount > 0 {
		fmt.Fprintf(b, " | %d binary files skipped", binaryCount)
	}
	b.WriteString("*\n")
}

func formatSize(bytes int64) string {
	switch {
	case bytes >= 1<<20:
		return fmt.Sprintf("%.1f MB", float64(bytes)/float64(1<<20))
	case bytes >= 1<<10:
		return fmt.Sprintf("%.1f KB", float64(bytes)/float64(1<<10))
	default:
		return fmt.Sprintf("%d B", bytes)
	}
}
